export const cities = [
  // Aceh
  { name: "Aceh Barat", slug: "aceh-barat" },
  { name: "Aceh Barat Daya", slug: "aceh-barat-daya" },
  { name: "Aceh Besar", slug: "aceh-besar" },
  { name: "Aceh Jaya", slug: "aceh-jaya" },
  { name: "Aceh Selatan", slug: "aceh-selatan" },
  { name: "Aceh Singkil", slug: "aceh-singkil" },
  { name: "Aceh Tamiang", slug: "aceh-tamiang" },
  { name: "Aceh Tengah", slug: "aceh-tengah" },
  { name: "Aceh Tenggara", slug: "aceh-tenggara" },
  { name: "Aceh Timur", slug: "aceh-timur" },
  { name: "Aceh Utara", slug: "aceh-utara" },
  { name: "Banda Aceh", slug: "banda-aceh" },
  { name: "Cengkareng", slug: "cengkareng" },
  { name: "Grogol Petamburan", slug: "grogol-petamburan" },
  { name: "Kalideres", slug: "kalideres" },
  { name: "Kebon Jeruk", slug: "kebon-jeruk" },
  { name: "Kembangan", slug: "kembangan" },
  { name: "Tambora", slug: "tambora" },
  { name: "Taman Sari", slug: "taman-sari" },
  { name: "Palmerah", slug: "palmerah" },

  // Sumatera Utara
  { name: "Medan", slug: "medan" },
  { name: "Binjai", slug: "binjai" },
  { name: "Pematangsiantar", slug: "pematangsiantar" },
  { name: "Tebing Tinggi", slug: "tebing-tinggi" },
  { name: "Sibolga", slug: "sibolga" },
  { name: "Tanjungbalai", slug: "tanjungbalai" },
  { name: "Padangsidempuan", slug: "padangsidempuan" },
  { name: "Kota Gunungsitoli", slug: "gunungsitoli" },
  { name: "Rantauprapat", slug: "rantauprapat" },
  
  // Sumatera Barat
  { name: "Padang", slug: "padang" },
  { name: "Bukittinggi", slug: "bukittinggi" },
  { name: "Payakumbuh", slug: "payakumbuh" },
  { name: "Solok", slug: "solok" },
  { name: "Pariaman", slug: "pariaman" },
  { name: "Padang Panjang", slug: "padang-panjang" },
  { name: "Sawahlunto", slug: "sawahlunto" },
  
  // Riau
  { name: "Pekanbaru", slug: "pekanbaru" },
  { name: "Dumai", slug: "dumai" },
  { name: "Bagansiapi-api", slug: "bagansiapi-api" },
  { name: "Tembilahan", slug: "tembilahan" },
  
  // Kepulauan Riau
  { name: "Batam", slug: "batam" },
  { name: "Tanjungpinang", slug: "tanjungpinang" },
  { name: "Bintan", slug: "bintan" },
  { name: "Karimun", slug: "karimun" },
  { name: "Kelapa Gading", slug: "kelapa-gading" },
  { name: "Koja", slug: "koja" },
  { name: "Cilincing", slug: "cilincing" },
  { name: "Tanjung Priok", slug: "tanjung-priok" },
  { name: "Pademangan", slug: "pademangan" },
  { name: "Penjaringan", slug: "penjaringan" },
  { name: "Bogor Tengah", slug: "bogor-tengah" },
  { name: "Bogor Timur", slug: "bogor-timur" },
  { name: "Bogor Barat", slug: "bogor-barat" },
  { name: "Bogor Utara", slug: "bogor-utara" },
  { name: "Bogor Selatan", slug: "bogor-selatan" },
  { name: "Tanah Sareal", slug: "tanah-sareal" },
  { name: "Cibinong", slug: "cibinong" },
  { name: "Cileungsi", slug: "cileungsi" },
  { name: "Cisarua", slug: "cisarua" },
  { name: "Gunung Putri", slug: "gunung-putri" },
  { name: "Jonggol", slug: "jonggol" },
  { name: "Parung", slug: "parung" },
  { name: "Sentul", slug: "sentul" },
  { name: "Leuwiliang", slug: "leuwiliang" },
  { name: "Dramaga", slug: "dramaga" },
  { name: "Ciomas", slug: "ciomas" },
  { name: "Puncak", slug: "puncak" },
  { name: "Taman Safari", slug: "taman-safari" },
  { name: "Gunung Salak", slug: "gunung-salak" },
  { name: "Kebun Raya Bogor", slug: "kebun-raya-bogor" },
  { name: "Curug Nangka", slug: "curug-nangka" },
  { name: "Sentul City", slug: "sentul-city" },
  { name: "Cikarang Utara", slug: "cikarang-utara" },
  { name: "Cikarang Selatan", slug: "cikarang-selatan" },
  { name: "Cikarang Barat", slug: "cikarang-barat" },
  { name: "Cikarang Timur", slug: "cikarang-timur" },
  { name: "Tambun Utara", slug: "tambun-utara" },
  { name: "Tambun Selatan", slug: "tambun-selatan" },
  { name: "Setu", slug: "setu" },
  { name: "Tarumajaya", slug: "tarumajaya" },
  { name: "Cibitung", slug: "cibitung" },
  { name: "Babelan", slug: "babelan" },
  { name: "Kedungwaringin", slug: "kedungwaringin" },
  { name: "Bekasi Utara", slug: "bekasi-utara" },
  { name: "Bekasi Timur", slug: "bekasi-timur" },
  { name: "Bekasi Selatan", slug: "bekasi-selatan" },
  { name: "Bekasi Barat", slug: "bekasi-barat" },
  { name: "Medan Satria", slug: "medan-satria" },
  { name: "Pondok Gede", slug: "pondok-gede" },
  { name: "Pondok Melati", slug: "pondok-melati" },
  { name: "Mustikajaya", slug: "mustikajaya" },
  { name: "Jatiasih", slug: "jatiasih" },
  { name: "Bantar Gebang", slug: "bantar-gebang" },
  { name: "Rawalumbu", slug: "rawalumbu" },
  
  // Jawa Barat
  { name: "Bandung", slug: "bandung" },
  { name: "Bandung Barat", slug: "bandung-barat" },
  { name: "Bekasi", slug: "bekasi" },
  { name: "Bogor", slug: "bogor" },
  { name: "Ciamis", slug: "ciamis" },
  { name: "Cianjur", slug: "cianjur" },
  { name: "Cimahi", slug: "cimahi" },
  { name: "Cirebon", slug: "cirebon" },
  { name: "Depok", slug: "depok" },
  { name: "Garut", slug: "garut" },
  { name: "Indramayu", slug: "indramayu" },
  { name: "Karawang", slug: "karawang" },
  { name: "Kuningan", slug: "kuningan" },
  { name: "Majalengka", slug: "majalengka" },
  { name: "Pangandaran", slug: "pangandaran" },
  { name: "Purwakarta", slug: "purwakarta" },
  { name: "Subang", slug: "subang" },
  { name: "Sukabumi", slug: "sukabumi" },
  { name: "Sumedang", slug: "sumedang" },
  { name: "Tasikmalaya", slug: "tasikmalaya" },
  { name: "Banjar", slug: "banjar" },
  { name: "Cilandak", slug: "cilandak" },
  { name: "Jagakarsa", slug: "jagakarsa" },
  { name: "Kebayoran Baru", slug: "kebayoran-baru" },
  { name: "Kebayoran Lama", slug: "kebayoran-lama" },
  { name: "Mampang Prapatan", slug: "mampang-prapatan" },
  { name: "Pancoran", slug: "pancoran" },
  { name: "Pasar Minggu", slug: "pasar-minggu" },
  { name: "Setiabudi", slug: "setiabudi" },
  { name: "Tebet", slug: "tebet" },
  { name: "Gambir", slug: "gambir" },
  { name: "Tanah Abang", slug: "tanah-abang" },
  { name: "Menteng", slug: "menteng" },
  { name: "Cempaka Putih", slug: "cempaka-putih" },
  { name: "Senen", slug: "senen" },
  { name: "Kemayoran", slug: "kemayoran" },
  { name: "Johar Baru", slug: "johar-baru" },
  { name: "Sawah Besar", slug: "sawah-besar" },
  { name: "Cakung", slug: "cakung" },
  { name: "Cipayung", slug: "cipayung" },
  { name: "Ciracas", slug: "ciracas" },
  { name: "Duren Sawit", slug: "duren-sawit" },
  { name: "Jatinegara", slug: "jatinegara" },
  { name: "Kramat Jati", slug: "kramat-jati" },
  { name: "Makasar", slug: "makasar" },
  { name: "Matraman", slug: "matraman" },
  { name: "Pasar Rebo", slug: "pasar-rebo" },
  { name: "Pulo Gadung", slug: "pulo-gadung" },
  
  // DKI Jakarta
  { name: "Jakarta", slug: "jakarta" },
  { name: "Jakarta Barat", slug: "jakarta-barat" },
  { name: "Jakarta Pusat", slug: "jakarta-pusat" },
  { name: "Jakarta Selatan", slug: "jakarta-selatan" },
  { name: "Jakarta Timur", slug: "jakarta-timur" },
  { name: "Jakarta Utara", slug: "jakarta-utara" },
  
  // Banten
  { name: "Serang", slug: "serang" },
  { name: "Cilegon", slug: "cilegon" },
  { name: "Tangerang", slug: "tangerang" },
  { name: "Tangerang Selatan", slug: "tangerang-selatan" },
  { name: "Pandeglang", slug: "pandeglang" },
  
  // Jawa Tengah
  { name: "Semarang", slug: "semarang" },
  { name: "Surakarta", slug: "surakarta" },
  { name: "Sragen", slug: "sragen" },
  { name: "Sukoharjo", slug: "sukoharjo" },
  { name: "Magelang", slug: "magelang" },
  { name: "Salatiga", slug: "salatiga" },
  { name: "Pati", slug: "pati" },
  { name: "Temanggung", slug: "temanggung" },
  
  // DI Yogyakarta
  { name: "Yogyakarta", slug: "yogyakarta" },
  { name: "Sleman", slug: "sleman" },
  { name: "Bantul", slug: "bantul" },
  { name: "Gunungkidul", slug: "gunungkidul" },
  { "name": "Wates", "slug": "wates" },
  { "name": "Sentolo", "slug": "sentolo" },
  { "name": "Galur", "slug": "galur" },
  { "name": "Pengasih", "slug": "pengasih" },
  { "name": "Lendah", "slug": "lendah" },
  { "name": "Kokap", "slug": "kokap" },
  { "name": "Temon", "slug": "temon" },
  { "name": "Jeruklegi", "slug": "jeruklegi" },
  { "name": "Samigaluh", "slug": "samigaluh" },
  { "name": "Wonosari", "slug": "wonosari" },
  { "name": "Playen", "slug": "playen" },
  { "name": "Paliyan", "slug": "paliyan" },
  { "name": "Nglipar", "slug": "nglipar" },
  { "name": "Karangmojo", "slug": "karangmojo" },
  { "name": "Semanu", "slug": "semanu" },
  { "name": "Tanjungsari", "slug": "tanjungsari" },
  { "name": "Patuk", "slug": "patuk" },
  { "name": "Nglipar", "slug": "nglipar" },
  { "name": "Bantul", "slug": "bantul" },
  { "name": "Srandakan", "slug": "srandakan" },
  { "name": "Pundong", "slug": "pundong" },
  { "name": "Kasihan", "slug": "kasihan" },
  { "name": "Imogiri", "slug": "imogiri" },
  { "name": "Pajangan", "slug": "pajangan" },
  { "name": "Dlingo", "slug": "dlingo" },
  { "name": "Bantul", "slug": "bantul" },
  { "name": "Gamping", "slug": "gamping" },
  { "name": "Mlati", "slug": "mlati" },
  { "name": "Turi", "slug": "turi" },
  { "name": "Maguwoharjo", "slug": "maguwoharjo" },
  { "name": "Ngaglik", "slug": "ngaglik" },
  { "name": "Sleman", "slug": "sleman" },
  { "name": "Depok", "slug": "depok" },
  { "name": "Cangkringan", "slug": "cangkringan" },
  { "name": "Prambanan", "slug": "prambanan" },
  { "name": "Kalasan", "slug": "kalasan" },
  { "name": "Gondokusuman", "slug": "gondokusuman" },
  { "name": "Gondomanan", "slug": "gondomanan" },
  { "name": "Kraton", "slug": "kraton" },
  { "name": "Mergangsan", "slug": "mergangsan" },
  { "name": "Ngampilan", "slug": "ngampilan" },
  { "name": "Danurejan", "slug": "danurejan" },
  { "name": "Pakualaman", "slug": "pakualaman" },
  { "name": "Umbulharjo", "slug": "umbulharjo" },
  { "name": "Wirobrajan", "slug": "wirobrajan" },
  { "name": "Mantrijeron", "slug": "mantrijeron" },
  { "name": "Yogyakarta", "slug": "yogyakarta" },
  { "name": "Sleman", "slug": "sleman" },
  { "name": "Bantul", "slug": "bantul" },
  { "name": "Gunungkidul", "slug": "gunungkidul" },
  { "name": "Kulon Progo", "slug": "kulon-progo" },
  
  // Jawa Timur
    { "name": "Surabaya", "slug": "surabaya" },
    { "name": "Malang", "slug": "malang" },
    { "name": "Probolinggo", "slug": "probolinggo" },
    { "name": "Batu", "slug": "batu" },
    { "name": "Madiun", "slug": "madiun" },
    { "name": "Blitar", "slug": "blitar" },
    { "name": "Jember", "slug": "jember" },
    { "name": "Kediri", "slug": "kediri" },
    { "name": "Tulungagung", "slug": "tulungagung" },
    { "name": "Banyuwangi", "slug": "banyuwangi" },
    { "name": "Sidoarjo", "slug": "sidoarjo" },
    { "name": "Lamongan", "slug": "lamongan" },
    { "name": "Gresik", "slug": "gresik" },
    { "name": "Jombang", "slug": "jombang" },
    { "name": "Situbondo", "slug": "situbondo" },
    { "name": "Tuban", "slug": "tuban" },
    { "name": "Sumenep", "slug": "sumenep" },
    { "name": "Pamekasan", "slug": "pamekasan" },
    { "name": "Bangkalan", "slug": "bangkalan" },
    { "name": "Mojokerto", "slug": "mojokerto" },
    { "name": "Ngawi", "slug": "ngawi" },
    { "name": "Pacitan", "slug": "pacitan" },
    { "name": "Magetan", "slug": "magetan" },
    { "name": "Trenggalek", "slug": "trenggalek" },
    { "name": "Ponorogo", "slug": "ponorogo" },
    { "name": "Blitar", "slug": "blitar" },
    { "name": "Bojonegoro", "slug": "bojonegoro" },
    { "name": "Kediri", "slug": "kediri" },
    { "name": "Mojokerto", "slug": "mojokerto" },
    { "name": "Sampang", "slug": "sampang" },
    { "name": "Bondowoso", "slug": "bondowoso" },
    { "name": "Situbondo", "slug": "situbondo" },
    { "name": "Ponorogo", "slug": "ponorogo" },
  
  
  
  // Bali
  { name: "Denpasar", slug: "denpasar" },
  { name: "Badung", slug: "badung" },
  { name: "Bangli", slug: "bangli" },
  { name: "Buleleng", slug: "buleleng" },
  { name: "Gianyar", slug: "gianyar" },
  { name: "Jembrana", slug: "jembrana" },
  { name: "Karangasem", slug: "karangasem" },
  { name: "Klungkung", slug: "klungkung" },
  { name: "Tabanan", slug: "tabanan" },
  { name: "Denpasar Utara", slug: "denpasar-utara" },
  { name: "Denpasar Timur", slug: "denpasar-timur" },
  { name: "Denpasar Selatan", slug: "denpasar-selatan" },
  { name: "Denpasar Barat", slug: "denpasar-barat" },
  { name: "Kuta", slug: "kuta" },
  { name: "Legian", slug: "legian" },
  { name: "Seminyak", slug: "seminyak" },
  { name: "Canggu", slug: "canggu" },
  { name: "Jimbaran", slug: "jimbaran" },
  { name: "Nusa Dua", slug: "nusa-dua" },
  { name: "Mengwi", slug: "mengwi" },
  { name: "Ubud", slug: "ubud" },
  { name: "Tegallalang", slug: "tegallalang" },
  { name: "Sukawati", slug: "sukawati" },
  { name: "Tampaksiring", slug: "tampaksiring" },
  { name: "Nusa Penida", slug: "nusa-penida" },
  { name: "Nusa Lembongan", slug: "nusa-lembongan" },
  { name: "Nusa Ceningan", slug: "nusa-ceningan" },
  { name: "Lovina", slug: "lovina" },
  { name: "Singaraja", slug: "singaraja" },
  { name: "Bali", slug: "bali" },
  
  // Nusa Tenggara Barat
  { "name": "Mataram", "slug": "mataram" },
  { "name": "Lombok Tengah", "slug": "lombok-tengah" },
  { "name": "Lombok Barat", "slug": "lombok-barat" },
  { "name": "Sumbawa", "slug": "sumbawa" },
  { "name": "Mataram", "slug": "mataram" },
  { "name": "Lombok Tengah", "slug": "lombok-tengah" },
  { "name": "Lombok Barat", "slug": "lombok-barat" },
  { "name": "Sumbawa", "slug": "sumbawa" },

  // Kecamatan di Kota Mataram
  { "name": "Ampenan", "slug": "ampenan" },
  { "name": "Cakranegara", "slug": "cakranegara" },
  { "name": "Selaparang", "slug": "selaparang" },

  // Kecamatan di Kabupaten Lombok Tengah
  { "name": "Praya", "slug": "praya" },
  { "name": "Praya Barat", "slug": "praya-barat" },
  { "name": "Praya Barat Daya", "slug": "praya-barat-daya" },
  { "name": "Batukliang", "slug": "batukliang" },
  { "name": "Batukliang Utara", "slug": "batukliang-utara" },
  { "name": "Janapria", "slug": "janapria" },
  { "name": "Kopang", "slug": "kopang" },
  { "name": "Kediri", "slug": "kediri" },
  { "name": "Jonggat", "slug": "jonggat" },
  { "name": "Labuapi", "slug": "labuapi" },

  // Kecamatan di Kabupaten Lombok Barat
  { "name": "Gerung", "slug": "gerung" },
  { "name": "Lembar", "slug": "lembar" },
  { "name": "Sekotong", "slug": "sekotong" },
  { "name": "Gunung Sari", "slug": "gunung-sari" },
  { "name": "Labuhan Lombok", "slug": "labuhan-lombok" },
  { "name": "Narmada", "slug": "narmada" },
  { "name": "Kuripan", "slug": "kuripan" },

  // Kecamatan di Kabupaten Sumbawa
  { "name": "Unter Iwes", "slug": "unter-iwes" },
  { "name": "Moyo Hulu", "slug": "moyo-hulu" },
  { "name": "Moyo Hilir", "slug": "moyo-hilir" },
  { "name": "Labangka", "slug": "labangka" },
  { "name": "Orong Telu", "slug": "orong-telu" },
  { "name": "Bula Timur", "slug": "bula-timur" },
  { "name": "Lantung", "slug": "lantung" },
  { "name": "Sumbawa Barat", "slug": "sumbawa-barat" },
  
  // Kecamatan di Kota Mataram
  { "name": "Ampenan", "slug": "ampenan" },
  { "name": "Cakranegara", "slug": "cakranegara" },
  { "name": "Selaparang", "slug": "selaparang" },
  
  // Kecamatan di Kabupaten Lombok Tengah
  { "name": "Praya", "slug": "praya" },
  { "name": "Praya Barat", "slug": "praya-barat" },
  { "name": "Praya Barat Daya", "slug": "praya-barat-daya" },
  { "name": "Batukliang", "slug": "batukliang" },
  { "name": "Batukliang Utara", "slug": "batukliang-utara" },
  { "name": "Janapria", "slug": "janapria" },
  { "name": "Kopang", "slug": "kopang" },
  { "name": "Kediri", "slug": "kediri" },
  { "name": "Jonggat", "slug": "jonggat" },
  { "name": "Labuapi", "slug": "labuapi" },
  
  // Kecamatan di Kabupaten Lombok Barat
  { "name": "Gerung", "slug": "gerung" },
  { "name": "Lembar", "slug": "lembar" },
  { "name": "Sekotong", "slug": "sekotong" },
  { "name": "Gunung Sari", "slug": "gunung-sari" },
  { "name": "Labuhan Lombok", "slug": "labuhan-lombok" },
  { "name": "Narmada", "slug": "narmada" },
  { "name": "Kuripan", "slug": "kuripan" },
  
  // Kecamatan di Kabupaten Sumbawa
  { "name": "Sumbawa", "slug": "sumbawa" },
  { "name": "Unter Iwes", "slug": "unter-iwes" },
  { "name": "Moyo Hulu", "slug": "moyo-hulu" },
  { "name": "Moyo Hilir", "slug": "moyo-hilir" },
  { "name": "Labangka", "slug": "labangka" },
  { "name": "Orong Telu", "slug": "orong-telu" },
  { "name": "Bula Timur", "slug": "bula-timur" },
  { "name": "Lantung", "slug": "lantung" },
  { "name": "Sumbawa Barat", "slug": "sumbawa-barat" },
  
  // Kalimantan Barat
  { name: "Pontianak", slug: "pontianak" },
  { name: "Singkawang", slug: "singkawang" },
  { name: "Sambas", slug: "sambas" },
  
  // Kalimantan Timur
  { name: "Samarinda", slug: "samarinda" },
  { name: "Balikpapan", slug: "balikpapan" },
  { name: "Bontang", slug: "bontang" },
  { name: "Kutai Kartanegara", slug: "kutai-kartanegara" },
  
  // Kalimantan Selatan
  { name: "Banjarmasin", slug: "banjarmasin" },
  { name: "Banjarbaru", slug: "banjarbaru" },
  
  // Sulawesi Utara
  { name: "Manado", slug: "manado" },
  { name: "Bitung", slug: "bitung" },
  { name: "Tomohon", slug: "tomohon" },
  
  // Sulawesi Selatan
  { name: "Makassar", slug: "makassar" },
  { name: "Parepare", slug: "parepare" },
  { name: "Palopo", slug: "palopo" },
  
  // Papua
  { name: "Jayapura", slug: "jayapura" },
  { name: "Sorong", slug: "sorong" },
  { name: "Merauke", slug: "merauke" },
  
  // Maluku
  { name: "Ambon", slug: "ambon" },
  
  // Nusa Tenggara Timur
  { name: "Kupang", slug: "kupang" },
  
  // Lampung
  { "name": "Bandar Lampung", "slug": "bandar-lampung" },
  { "name": "Metro", "slug": "metro" },

  // Kecamatan di Kota Bandar Lampung
  { "name": "Teluk Betung Barat", "slug": "teluk-betung-barat" },
  { "name": "Teluk Betung Selatan", "slug": "teluk-betung-selatan" },
  { "name": "Teluk Betung Timur", "slug": "teluk-betung-timur" },
  { "name": "Bumi Waras", "slug": "bumi-waras" },
  { "name": "Sukarame", "slug": "sukarame" },
  { "name": "Sukaraja", "slug": "sukaraja" },
  { "name": "Rajabasa", "slug": "rajabasa" },
  { "name": "Tanjung Karang Barat", "slug": "tanjung-karang-barat" },
  { "name": "Tanjung Karang Timur", "slug": "tanjung-karang-timur" },
  { "name": "Kedaton", "slug": "kedaton" },
  { "name": "Langkapura", "slug": "langkapura" },
  { "name": "Way Halim", "slug": "way-halim" },

  // Kecamatan di Kota Metro
  { "name": "Metro Barat", "slug": "metro-barat" },
  { "name": "Metro Pusat", "slug": "metro-pusat" },
  { "name": "Metro Timur", "slug": "metro-timur" },
  { "name": "Metro Utara", "slug": "metro-utara" },
  
  // Bengkulu
  { name: "Bengkulu", slug: "bengkulu" },
  { "name": "Ratu Agung", "slug": "ratu-agung" },
  { "name": "Sungai Serut", "slug": "sungai-serut" },
  { "name": "Gading Cempaka", "slug": "gading-cempaka" },
  { "name": "Muara Bangkahulu", "slug": "muara-bangkahulu" },
  { "name": "Teluk Segara", "slug": "teluk-segara" },
  { "name": "Kampung Melayu", "slug": "kampung-melayu" },
  { "name": "Selebar", "slug": "selebar" },
  { "name": "Bengkulu Selatan", "slug": "bengkulu-selatan" },
  
  // Sumatera Selatan
  { name: "Palembang", slug: "palembang" },
  { name: "Prabumulih", slug: "prabumulih" },
  { "name": "Ilir Barat I", "slug": "ilir-barat-i" },
  { "name": "Ilir Barat II", "slug": "ilir-barat-ii" },
  { "name": "Kemuning", "slug": "kemuning" },
  { "name": "Kertapati", "slug": "kertapati" },
  { "name": "Seberang Ulu I", "slug": "seberang-ulu-i" },
  { "name": "Seberang Ulu II", "slug": "seberang-ulu-ii" },
  { "name": "Sako", "slug": "sako" },
  { "name": "Alang-Alang Lebar", "slug": "alang-alang-lebar" },
  { "name": "Plaju", "slug": "plaju" },
  { "name": "Bukit Kecil", "slug": "bukit-kecil" },
  { "name": "Ilir Timur I", "slug": "ilir-timur-i" },
  { "name": "Ilir Timur II", "slug": "ilir-timur-ii" },

  // Kecamatan di Kota Prabumulih
  { "name": "Prabumulih Timur", "slug": "prabumulih-timur" },
  { "name": "Prabumulih Barat", "slug": "prabumulih-barat" },
  { "name": "Prabumulih Selatan", "slug": "prabumulih-selatan" },
  { "name": "Prabumulih Utara", "slug": "prabumulih-utara" },
  
  // Kalimantan Tengah
  { name: "Palangka Raya", slug: "palangka-raya" },
  { "name": "Pahandut", "slug": "pahandut" },
  { "name": "Bukit Batu", "slug": "bukit-batu" },
  { "name": "Sebangau", "slug": "sebangau" },
  { "name": "Jekan Raya", "slug": "jekan-raya" },
  { "name": "Sabangau", "slug": "sabangau" },
  
  // Kalimantan Utara
  { name: "Tanjung Selor", slug: "tanjung-selor" },
  
  // Gorontalo
  { name: "Gorontalo", slug: "gorontalo" },
  { "name": "Hulonthalangi", "slug": "hulonthalangi" },
  { "name": "Dumbo Raya", "slug": "dumbo-raya" },
  { "name": "Kota Utara", "slug": "kota-utara" },
  { "name": "Kota Tengah", "slug": "kota-tengah" },
  { "name": "Kota Selatan", "slug": "kota-selatan" },
  
  // Sulawesi Tenggara
  { name: "Kendari", slug: "kendari" },
  { "name": "Kendari Barat", "slug": "kendari-barat" },
  { "name": "Kendari Selatan", "slug": "kendari-selatan" },
  { "name": "Kendari Timur", "slug": "kendari-timur" },
  { "name": "Kendari Utara", "slug": "kendari-utara" },
  { "name": "Poasia", "slug": "poasia" },
  { "name": "Abeli", "slug": "abeli" },
  { "name": "Baruga", "slug": "baruga" },
  { "name": "Wuawua", "slug": "wuawua" },
  
  // Sulawesi Barat
  { name: "Mamuju", slug: "mamuju" },
  { "name": "Simboro", "slug": "simboro" },
  { "name": "Tamalatea", "slug": "tamalatea" },
  { "name": "Budong-Budong", "slug": "budong-budong" },
  
  // Maluku Utara
  { name: "Ternate", slug: "ternate" },
  { "name": "Ternate Selatan", "slug": "ternate-selatan" },
  { "name": "Ternate Tengah", "slug": "ternate-tengah" },
  { "name": "Ternate Utara", "slug": "ternate-utara" },
  { "name": "Pulau Ternate", "slug": "pulau-ternate" },
  { "name": "Ternate Timur", "slug": "ternate-timur" },
  
  // Papua Barat
  { name: "Manokwari", slug: "manokwari" },
  { name: "Sorong", slug: "sorong" },
];
